AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation Nested NetworkAcl Stack

Parameters:
  Name: 
    Type: String
    Description: Enter NetworkAcl name
  
Resources:
  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      Tags:
        - Key: Name
          Value: !Join [ "", [ !ImportValue VPCName, "-", !Ref Name ] ]
      VpcId: !ImportValue VPCID

Outputs:
  NetworkAclId:
    Description: The NetworkAcl ID
    Value: !Ref NetworkAcl
    Export:
      Name: !Join [ "", [ !Ref Name, "ID" ] ]