AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation Nested RouteTable Stack

Parameters:
  Name: 
    Type: String
    Description: Enter RouteTable name
  
Resources:
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags:
        - Key: Name
          Value: !Join [ "", [ !ImportValue VPCName, "-" , !Ref Name ] ]
      VpcId: !ImportValue VPCID

Outputs:
  RouteTableId:
    Description: The RouteTable ID
    Value: !Ref RouteTable
    Export:
      Name: !Join [ "", [ !Ref Name, "ID" ] ]
