---
AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation Nested Instance Stack

Parameters: 
  Name:
    Type: String
    Description: Enter Instance name
  SecurityGroupIds:
    Type: String
    Description: Enter SecurityGroupIds list
  SubnetId:
    Type: String
    Description: Enter SubnetId
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Enter AvailabilityZone

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties: 
      SubnetId: !Ref SubnetId
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: ami-0d5075a2643fdf738
      InstanceType: t2.micro
      KeyName: Wolly-NCalifornia
      SecurityGroupIds: !Split [",", !Ref SecurityGroupIds]
      Tags: 
        - Key: Name
          Value: !Join [ "", [ !ImportValue VPCName, "-", !Ref Name ] ]
      UserData: 
        Fn::Base64:
          !Sub |
            #!/bin/bash
            echo "-------------------START-------------------"
            amazon-linux-extras install nginx1

            mkdir -p /var/www/hellowebsite
            echo "<html><body><center><h1>Hello from $HOSTNAME</h1></center></body></html>" > /var/www/hellowebsite/index.html

            echo -e "server {\n\tlisten 80;\n\tlisten [::]:80;\n\troot /var/www/hellowebsite;\n\tindex index.html;\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}" > /etc/nginx/conf.d/hello-website.conf

            systemctl enable nginx
            systemctl start nginx
            echo "-------------------FINISH------------------"

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref Instance
    Export:
      Name: !Join [ "", [ !Ref Name, "ID" ] ]
    
