---
# tasks file for npm
- name: add NodeSource repository for Node.js
  yum:
    name: https://rpm.nodesource.com/pub_{{ node_version }}.x/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm
    state: present

- name: Install nodejs
  yum:
    name: nodejs
    state: present
    update_cache: yes
