# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Minsk /etc/localtime", run: "always"
  
  config.vm.define "webui" do |vm|
    vm.vm.box = "ubuntu18.04"
    vm.vm.hostname = "webui"
    vm.vm.network :private_network, ip: "192.168.9.15"
    
  end
  
  config.vm.define "logstash" do |vm|
    vm.vm.box = "ubuntu18.04"
    vm.vm.hostname = "logstash"
    vm.vm.network :private_network, ip: "192.168.9.16"
    
  end
  
  config.vm.define "haproxy" do |vm|
    vm.vm.box = "ubuntu18.04"
    vm.vm.hostname = "haproxy"
    vm.vm.network :private_network, ip: "192.168.9.17"
    
  end
  
end
