---
AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation Nested Subnets Stack

Resources:
  PublicSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/wolly.test-cloud-formation/VPC/Subnets/Subnet/Subnet_stack.yml
      Parameters:
        CidrBlock: 10.0.11.0/24
        MapPublicIpOnLaunch: 'true'
        Name: PublicSubnetA
        VpcId: !ImportValue VPCID
        AvailabilityZone: !Select 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
  
  PrivateSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/wolly.test-cloud-formation/VPC/Subnets/Subnet/Subnet_stack.yml
      Parameters:
        CidrBlock: 10.0.12.0/24
        MapPublicIpOnLaunch: 'false'
        Name: PrivateSubnetA
        VpcId: !ImportValue VPCID
        AvailabilityZone: !Select 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'

  PublicSubnetB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/wolly.test-cloud-formation/VPC/Subnets/Subnet/Subnet_stack.yml
      Parameters:
        CidrBlock: 10.0.21.0/24
        MapPublicIpOnLaunch: 'true'
        Name: PublicSubnetB
        VpcId: !ImportValue VPCID
        AvailabilityZone: !Select 
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'

  PrivateSubnetB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/wolly.test-cloud-formation/VPC/Subnets/Subnet/Subnet_stack.yml
      Parameters:
        CidrBlock: 10.0.22.0/24
        MapPublicIpOnLaunch: 'false'
        Name: PrivateSubnetB
        VpcId: !ImportValue VPCID
        AvailabilityZone: !Select 
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'
