---
AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation Nested SecurityGroup Stack

Parameters:
  Name:
    Type: String
    Description: Enter SecurityGroup name
  Description:
    Type: String
    Description: Enter SecurityGroup name

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: !Ref Description
      GroupName: !Ref Name
      Tags: 
        - Key: Name
          Value: !Join [ "", [ !ImportValue VPCName, "-", !Ref Name ] ]
      VpcId: !ImportValue VPCID

Outputs:
  GroupId:
    Description: The SecurityGroup ID
    Value: !GetAtt SecurityGroup.GroupId
    Export:
      Name: !Join [ "", [ !Ref Name, "ID" ] ]