# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.define "app" do |app|
    app.vm.network "forwarded_port", guest: 22, host: 22022
    app.vm.network "forwarded_port", guest: 80, host: 22080
    app.vm.network "forwarded_port", guest: 443, host: 22443
    app.vm.network "forwarded_port", guest: 3306, host: 22306
    app.vm.box = "ubuntu18.04"
    app.vm.network :private_network, ip: "192.168.60.6"
    
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
    end
  end

end
